name: Upload IPA to App Store

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Download IPA from GitHub Releases
        run: |
          curl -L "https://github.com/Anzi15/upload-ipa/releases/download/v1.0/App.1.ipa" -o App.ipa
          ls -lh App.ipa

      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file App.ipa \
            --username "${{ secrets.APPLE_ID }}" \
            --password "${{ secrets.APPLE_PASSWORD }}" \
            --asc-provider "${{ secrets.APPLE_TEAM_ID }}"
